# Generated by Django 4.1 on 2022-10-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0002_alter_abastecer_usuario_alter_despesa_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecer',
            name='odometro',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
