# Generated by Django 4.1 on 2022-10-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0005_alter_abastecer_preco_alter_veiculo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecer',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='abastecer',
            name='odometro',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Odômetro'),
        ),
        migrations.AlterField(
            model_name='abastecer',
            name='qtd_litros',
            field=models.FloatField(verbose_name='Litros abastecidos'),
        ),
        migrations.AlterField(
            model_name='abastecer',
            name='tipo_combustivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carro.tipocombustivel', verbose_name='Tipo de combustível'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='observacao',
            field=models.CharField(blank=True, max_length=144, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='odometro',
            field=models.FloatField(verbose_name='Odômetro'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='opcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carro.tipodespesa', verbose_name='Tipo de despesa'),
        ),
        migrations.AlterField(
            model_name='troca_oleo',
            name='km_atual',
            field=models.FloatField(verbose_name='KM atual'),
        ),
        migrations.AlterField(
            model_name='troca_oleo',
            name='proxima_troca',
            field=models.FloatField(verbose_name='Próxima troca'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='odometro',
            field=models.FloatField(verbose_name='Odômetro'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_combustivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='veiculos', to='carro.tipocombustivel', verbose_name='Tipo de combustível'),
        ),
    ]
