# Generated by Django 4.1 on 2022-10-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0006_alter_abastecer_data_alter_abastecer_odometro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecer',
            name='data',
            field=models.DateField(),
        ),
    ]
