# Generated by Django 4.1 on 2022-10-16 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carro', '0008_alter_abastecer_odometro_alter_despesa_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecer',
            name='placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carro.veiculo'),
        ),
        migrations.AlterField(
            model_name='abastecer',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carro.veiculo'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='troca_oleo',
            name='placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carro.veiculo'),
        ),
        migrations.AlterField(
            model_name='troca_oleo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to=settings.AUTH_USER_MODEL),
        ),
    ]
