# Generated by Django 4.1 on 2022-10-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0009_alter_abastecer_placa_alter_abastecer_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecer',
            name='odometro',
            field=models.FloatField(verbose_name='Odômetro'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='odometro',
            field=models.FloatField(verbose_name='Odômetro'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='odometro',
            field=models.FloatField(verbose_name='Odômetro'),
        ),
    ]
