# Generated by Django 4.1 on 2022-10-16 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carro', '0004_alter_veiculo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecer',
            name='preco',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='veiculos', to=settings.AUTH_USER_MODEL),
        ),
    ]
